### ISSUE TITLE
unable to build small java example via maven at the command line

### ISSUE THREAD

**Issue by carljmosca** [LorenzoBettini/packtpub-xtext-book-2nd-examples#28]
From the org.example.smalljava.parent directory, building from the command line with maven fails with a ClassNotFoundException:

[org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.main()] ERROR mf.mwe2.launch.runtime.Mwe2Launcher  - org/slf4j/LoggerFactory
java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory

Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

**Comment by LorenzoBettini** [comment]
You have to run the Maven build from the `org.example.parent` project. You can build a single DSL using the corresponding profile.
For example, for SmallJava

```
mvn -f org.example.parent/pom.xml clean verify -Psmalljava
```

This works, I've just tried that.

**Comment by carljmosca** [comment]
There must be something else wrong.  I am getting the same error message using the above command (which is very similar to what I was already doing).

**Comment by LorenzoBettini** [comment]
Are you sure you're using the latest version of the Git repository? (currently based on Xtext 2.17.0)

Some times, cleaning the `.m2/repository` might help.

If this does not solve the problem, I need some more information, e.g., OS version and the full stack trace.

**Comment by LorenzoBettini** [comment]
By the way, you're not using Maven 3.6.1 are you? That version has serious problems for Maven/Tycho projects

**Comment by carljmosca** [comment]
I removed my ~/.m2/repository directory before I opened the issue but I suspect there may have been unresolved issues that I missed because I just repeated that and after noticing a good number of warning/retries (such as the one below), it was eventually successful.

[WARNING] Some attempts to read artifact osgi.bundle,org.eclipse.xtext.generator,2.17.0.v20190304-0626 failed:
[WARNING]    An error occurred while transferring artifact canonical: osgi.bundle,org.eclipse.xtext.generator,2.17.0.v20190304-0626 from repository http://download.eclipse.org/releases/2019-03/201903201000:
[WARNING]       Retry another mirror:
[WARNING]          Unable to connect to repository http://mirror.cc.vt.edu/pub/eclipse/releases/2019-03/201903201000/plugins/org.eclipse.xtext.generator_2.17.0.v20190304-0626.jar

**Comment by LorenzoBettini** [comment]
Yes, sometimes p2 mirrors might be flaky. When that happens, you might want to disable mirrors passing this command line property in the build `-Dtycho.disableP2Mirrors=true`.

**Comment by carljmosca** [comment]
Thank you.
