### ISSUE TITLE
Second edition, Chapter 13 (Extending Xbase) appears to have a typo on page 379

### ISSUE THREAD

**Issue by nbhusare** [LorenzoBettini/packtpub-xtext-book-2nd-examples#43]
Here is the excerpt from the second edition of the book, page 379 - we implement, `internalToConvertedExpression` by simply generating in the Java code a reference to the synthetic variable associated to the original eval expression. If I understand it correctly, the instruction is to override the method `internalToConvertedExpression` and not `internalToxpression`.

Code example from the book.
```
override protected internalToxpression(XExpression obj, ITreeAppendable a) {
  if (obj instanceof EvalExpression)
  a.append(getVarName(obj, a))
else
  super.internalToConvertedExpression(obj, a)
 }
}
```

**Comment by LorenzoBettini** [comment]
Yes, exactly. That was a problem introduced during the publishing phase by the publisher...
