### ISSUE TITLE
EntitiesQuickfixProvider.xtend copy/paste error

### ISSUE THREAD

**Issue by sxhickman** [LorenzoBettini/packtpub-xtext-book-2nd-examples#5]
capitalizeEntityNameFirstLetter appears to have content copied from createMissingEntity

**Comment by LorenzoBettini** [comment]
You mean in the source code of the example, not in the book right?
I'll fix ASAP!
Thanks!

**Comment by sxhickman** [comment]
Correct - the GitHub source. The book appears to be correct.
