### ISSUE TITLE
Entities runtime does not create src-gen folder

### ISSUE THREAD

**Issue by sxhickman** [LorenzoBettini/packtpub-xtext-book-2nd-examples#6]
When you start a runtime instance of Eclipse based on the Entities meta-model, create a .entities file and then save it, an entities-gen folder is created rather than a src-gen folder.

This isn't incorrect, per se - but it is inconsistent with the book content in the 'Integration with the Eclipse Build Mechanism' section. I see that you include at the end of the section a comment that this illustrates that the name 'src-gen' isn't hardcoded.  Having said that, the text appears to be inconsistent with the sample code for readers of Ch. 5.

**Comment by sxhickman** [comment]
I see now that you do in fact include this at the end of the chapter.  However, the inconsistency with the book remains.

**Comment by LorenzoBettini** [comment]
The "entities-gen" folder is explained and implemented in Chapter 6 ("Customizing Xtext Components"). If you use the finished examples then you will also see the final implementation. While, when reading the book, if you try to do the code yourself, you'll get the src-gen folder. This "workflow" (do the examples yourself while reading, or try the final complete example with the final behavior) is explained at the beginning of the book.
Or did I miss what you were suggesting?

**Comment by sxhickman** [comment]
I just finished a section in Chapter 5 (so I haven't yet seen Ch. 6).  And I trust that you're correct in that if I actually manually do everything, I'll get the defaults rather than what is in the samples.  Since I've had several weeks of exposure to XText prior to the benefit of your book, I've just been reading rapidly and cross checking with the samples you provide rather than manually recreating them. 

It may not be worth making a change just based on my experience.

**Comment by LorenzoBettini** [comment]
So you agree to close this issue, don't you?
